name: rovelle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  image_picker: ^1.1.2
  flutter_lints: ^6.0.0
  cloud_firestore: ^6.0.0
  provider: ^6.1.5
  firebase_storage: ^13.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.1
  google_sign_in_android: ^6.2.1



flutter:
  uses-material-design: true

flutter_icons:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
